### PR TITLE
Export spot counts

### PR DESCRIPTION
**Pull request by stefanhahmann**
This PR adds a new plugin that can be used to write spot counts per timepoint to a single CSV file

Resolves https://github.com/mastodon-sc/mastodon-deep-lineage/issues/73

### CODE REVIEW

**Comment by xulman** [comment]
btw, there's Plugins -> Exports -> Export spots counts

Screenshot_20240216_151429

(not exactly the same, I know... just FYI)

**Comment by stefanhahmann** [comment]
> btw, there's Plugins -> Exports -> Export spots counts
> 
> Screenshot_20240216_151429
> 
> (not exactly the same, I know... just FYI)

I am aware of this. My suggestion in this PR is to both functions in the same (sub-)menu:

grafik

**Comment by xulman** [comment]
oh, wow!
didn't occur to me earlier
sorry
this is nice! very nice, thank you

**Review by maarzt — CHANGES_REQUESTED** [review]
Looks good. I would like to refactor some minor things and afterwards merge the PR. Would that be OK for you?

**Pull request merged**
